Gerenciador de Consultas Médicas/Controllers/agendaController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Gerenciador_de_Consultas_Médicas.Models;
using PagedList;

namespace Gerenciador_de_Consultas_Médicas.Controllers
{
    public class agendaController : Controller
    {
        private DominioContainer db = new DominioContainer();
        
        // GET: agenda
        public ActionResult Index(int? idMedico, int? page)
        {
            deletarAgendaAntiga();

            //quantidade de itens
            int pageSize = 10;
            //numero da pag, se for nulo retorna 1
            int pageNumber = (page ?? 1);

            if (idMedico == null)
            {
                idMedico = Convert.ToInt16(Session["idUsuario"]);
            }
            
            var agendaSet = db.agendaSet.Where(a => a.medicos_idMedico == idMedico && a.horarioAgendado != "Check-out realizado").
            OrderByDescending(a => a.horarioAgendado).ThenBy(a => a.data);

            ViewBag.idMedico = idMedico;

            return View(agendaSet.ToPagedList(pageNumber, pageSize));
            
        }

        //Index de quando o Adm da clínica chama
        public ActionResult IndexAdm(agendaMedicoCadastroViewModel idMed)
        {
            int id = idMed.idMedico;

            return RedirectToAction("Index", new { idMedico = id });
        }

        public ActionResult verificarAgenda(infParaAgendaEConsultaViewModel medico,int? idMedico, int? page)
        {
            
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            if (medico == null)
            {
                var query = from a in db.agendaSet
                            where a.medicos_idMedico == idMedico && a.horarioAgendado == null
                            from m in db.medicosSet
                            where m.idMedico == medico.idMedico
                            orderby a.data
                            select new infParaAgendaEConsultaViewModel
                            {
                                idClinica = m.clinicas_idClinica,
                                idMedico = m.idMedico,
                                nomeMedico = m.nome,
                                data = a.data,
                                horarios = a.horarioAtendimento
                            };

                ViewBag.idMedico = idMedico;

                return View(query.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                var query = from a in db.agendaSet
                            where a.medicos_idMedico == medico.idMedico && a.horarioAgendado == null
                            from m in db.medicosSet
                            where m.idMedico == medico.idMedico
                            orderby a.data
                            select new infParaAgendaEConsultaViewModel
                            {
                                idClinica = m.clinicas_idClinica,
                                idMedico = m.idMedico,
                                nomeMedico = m.nome,
                                data = a.data,
                                horarios = a.horarioAtendimento
                            };

                ViewBag.idMedico = medico.idMedico;

                return View(query.ToPagedList(pageNumber, pageSize));
            }
        }

        public ActionResult confirmarConsulta(int idMedico, string nomeMedico, string data, string horario, int idClinica)
        {
            infParaAgendaEConsultaViewModel marcar = new infParaAgendaEConsultaViewModel();
            marcar.nomeMedico = nomeMedico;
            marcar.idMedico = idMedico;
            marcar.data = data;
            marcar.horarios = horario;
            marcar.idClinica = idClinica;

            return RedirectToAction("confirmarConsulta", "consultas", marcar);
        }
        
        public void deletarAgendaAntiga()
        {
            var dateAndTime = DateTime.Now;
            var today = dateAndTime.Date;
            var agenda = db.agendaSet.ToList().
                Where(a => a.horarioAgendado == null && Convert.ToDateTime(a.data) < today).OrderBy(a => a.data);

            if (!agenda.Any())
                return;

            foreach(var a in agenda)
                db.agendaSet.Remove(a);

            db.SaveChanges();
        }


        // GET: agenda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            agenda agenda = db.agendaSet.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            return View(agenda);
        }

        // GET: agenda/Create
        public ActionResult Create()
        {
            ViewBag.medicos_idMedico = new SelectList(db.medicosSet, "idMedico", "nome");
            
            return View();
        }

        // POST: agenda/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(agendaMedicoCadastroViewModel dadosAgenda)
        {
            var inicio = dadosAgenda.inicioAtendimento;
            var fim = dadosAgenda.fimAtendimento;

            int id = Convert.ToInt16(Session["idUsuario"]);
            agenda agenda = new agenda();
            agenda.medicos_idMedico = id;
            agenda.data = dadosAgenda.data;

            int idClinica = Convert.ToInt16(Session["idClinica"]);
            var duracaoConsultas = db.clinicasSet.Where(c => c.idClinica == idClinica).Select(c => c.duracaoConsultas).Single();
            TimeSpan intervalo = TimeSpan.FromMinutes(duracaoConsultas);

            if (ModelState.IsValid && inicio < fim)
            {
                while (inicio <= fim)
                {
                    agenda.horarioAtendimento = Convert.ToString(inicio);
                    inicio = inicio + intervalo;
                    db.agendaSet.Add(agenda);
                    db.SaveChanges();
                }
                return RedirectToAction("Index", dadosAgenda.idMedico);
            }
            
            return View(dadosAgenda);
        }

        // GET: agenda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            agenda agenda = db.agendaSet.Find(id);
            
            if (agenda == null)
            {
                return HttpNotFound();
            }
            
            return View(agenda);
        }

        // POST: agenda/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(agenda agenda)
        {
            int id = Convert.ToInt16(Session["idUsuario"]);
            agenda.medicos_idMedico = id;
            if (ModelState.IsValid)
            {
                db.Entry(agenda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", agenda.medicos_idMedico);
            }
            
            return View(agenda);
        }

        // GET: agenda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            agenda agenda = db.agendaSet.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            return View(agenda);
        }

        // POST: agenda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            agenda agenda = db.agendaSet.Find(id);
            db.agendaSet.Remove(agenda);
            db.SaveChanges();
            return RedirectToAction("Index", agenda.medicos_idMedico);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gerenciador de Consultas Médicas/Controllers/medicosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gerenciador_de_Consultas_Médicas.Models;

namespace Gerenciador_de_Consultas_Médicas.Controllers
{
    public class medicosController : Controller
    {
        private DominioContainer db = new DominioContainer();

        // GET: medicos
        public ActionResult Index()
        {
            int idUsuario = Convert.ToInt16(Session["idUsuario"]);
            int idClinica = Convert.ToInt16(Session["idClinica"]);

            if (Convert.ToInt16(Session["adm"]) == 0)
            {
                var medico = db.medicosSet.Where(m => m.idMedico == idUsuario);
                return View(medico.ToList());
            }
            else
            {
                var medico = db.medicosSet.Where(m => m.clinicas_idClinica == idClinica);
                return View(medico.ToList());
            }
        }

        // GET: medicos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
                id = Convert.ToInt16(Session["idUsuario"]);

            medicos medicos = db.medicosSet.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }

            return View(medicos);
        }

        // GET: medicos/Create
        public ActionResult Create()
        {            
            ViewBag.especialidades_idEspecialidade = new SelectList(db.especialidadesSet, "idEspecialidade", "ds_especialidade");
            return View();
        }

        // POST: medicos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idMedico,nome,email,senha,confirmarSenha,preco,situacao,especialidades_idEspecialidade,clinicas_idClinica")] medicos medicos)
        {
            medicos.clinicas_idClinica = Convert.ToInt16(Session["idClinica"]);
            medicos.situacao = 1;
            if (Session["idUsuario"] == null)
                medicos.adm = 1;
            else
                medicos.adm = 0;

            if (ModelState.IsValid)
            {
                db.medicosSet.Add(medicos);
                db.SaveChanges();

                if (Session["idUsuario"] != null)
                    return RedirectToAction("Index");
                else
                    return View("_LayoutCadastroRealizado");
            }
            
            ViewBag.especialidades_idEspecialidade = new SelectList(db.especialidadesSet, "idEspecialidade", "ds_especialidade");
            return View(medicos);
        }

        // GET: medicos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            medicos medicos = db.medicosSet.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            //ViewBag.especialidades_idEspecialidade = new SelectList(db.especialidadesSet, "idEspecialidade", "ds_especialidade", medicos.especialidades_idEspecialidade);
            ViewBag.especialidades_idEspecialidade = new SelectList(db.especialidadesSet, "idEspecialidade", "ds_especialidade");
            ViewBag.clinicas_idClinica = new SelectList(db.clinicasSet, "idClinica", "nome", medicos.clinicas_idClinica);
            return View(medicos);
        }

        // POST: medicos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idMedico,nome,email,senha,confirmarSenha,preco,situacao,especialidades_idEspecialidade")] medicos medicos)
        //[Bind(Include = "idMedico,nome,email,senha,preco,situacao")]
        {
            int id = Convert.ToInt16(Session["idClinica"]);
            medicos.clinicas_idClinica = id;
            
            if (ModelState.IsValid)
            {
                if (Convert.ToString(Session["tipoUsuario"]) == "Adm" && medicos.idMedico == Convert.ToUInt16(Session["idUsuario"]))
                    medicos.adm = 1;
                else
                    medicos.adm = 0;
                db.Entry(medicos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
           
            ViewBag.especialidades_idEspecialidade = new SelectList(db.especialidadesSet, "idEspecialidade", "ds_especialidade", medicos.especialidades_idEspecialidade);
            return View(medicos);
        }

        
        // GET: medicos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            medicos medicos = db.medicosSet.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            return View(medicos);
        }

        // POST: medicos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            medicos medicos = db.medicosSet.Find(id);
            db.medicosSet.Remove(medicos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //listar os medicos da clínica selecionada, com os dados de sua agenda.
        public ActionResult listarMedicos(ClinicasPacMedViewModel cli)
        {
            var query = (from m in db.medicosSet
                         where m.clinicas_idClinica == cli.idClinica
                         from e in db.especialidadesSet
                         where e.idEspecialidade == m.especialidades_idEspecialidade
                         select new perfilMedicoViewModel
                         {
                             idMedico = m.idMedico,
                             nome = m.nome,
                             especialidade = e.ds_especialidade,
                             preco = m.preco,
                             emailMedico = m.email
                         });

            return View(query.ToList());
        }

        public ActionResult verAgenda(int idMedico)
        {
            agendaMedicoCadastroViewModel idMed = new agendaMedicoCadastroViewModel();
            idMed.idMedico = idMedico;

            return RedirectToAction("IndexAdm", "agenda", idMed);
        }

        public ActionResult verificarAgenda(int idMedico)
        {
            infParaAgendaEConsultaViewModel agenda = new infParaAgendaEConsultaViewModel();
            agenda.idMedico = idMedico;

            return RedirectToAction("verificarAgenda", "agenda", agenda);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gerenciador de Consultas Médicas/Views/Shared/Rodape.cshtml
<footer class="text-center">
    <div class="content-wrapper">
        <div class="float-left">
            <p id="text">&copy; @DateTime.Now.Year - Desenvolvido por <a href="https://www.linkedin.com/comm/profile/view?id=AAsAABMW19cBzqKZW5c0mSlFhNOQ7kV_PvAs11c&midToken=AQFeGVFM3TG9WA&trk=eml-job_alert_email-header-6-profile&trkEmail=eml-job_alert_email-header-6-profile-null-5aodef~iuvsbaov~x7" target="_blank">Marcio de Oliveira</a></p>
        </div>
    </div>
</footer>

Gerenciador de Consultas Médicas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div id="menu" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Content/Imagens/medical_icon_1.png" />
                @Html.ActionLink("Consulta fácil", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
        <hr />
    </div>
    @Html.Partial("Rodape")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Gerenciador de Consultas Médicas/Views/Shared/_LayoutAdministrador.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div id="menu" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Content/Imagens/medical_icon_1.png" />
                @Html.ActionLink("Consulta fácil", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Clínica", "Index", "clinicas")</li>
                    <li>@Html.ActionLink("Médicos", "Index", "medicos")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Html.Partial("Rodape")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Gerenciador de Consultas Médicas/Views/Shared/_LayoutCadastroRealizado.cshtml
@{
    ViewBag.Title = "_LayoutCadastroRealizado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cadastro</h2>
<div><h4>Cadastro realizado com sucesso. Deseja fazer o @Html.ActionLink("login", "Login", "Account") agora?</h4> 
    <img src="~/Content/Imagens/confirmation.png" />  </div>

Gerenciador de Consultas Médicas/Views/Shared/_LayoutDadosAlterados.cshtml
@{
    ViewBag.Title = "_LayoutCadastroRealizado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cadastro</h2>
<h4>Dados alterados com sucesso!</h4>

Gerenciador de Consultas Médicas/Views/Shared/_LayoutMedico.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div id="menu" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Content/Imagens/medical_icon_1.png" />
                @Html.ActionLink("Consulta fácil", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Agenda", "Index", "agenda")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    @Html.Partial("Rodape")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Gerenciador de Consultas Médicas/Views/Shared/_LayoutPaciente.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCrIvn3ekmPC6RsBuegSo0jo7epygCRcEo&">
    </script>
</head>
<body onload="initialize();">
    <div id="menu" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Content/Imagens/medical_icon_1.png" />
                @Html.ActionLink("Consulta fácil", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Consultas", "Index", "consultas")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    @Html.Partial("Rodape")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>