Gerenciador de Consultas Médicas/Models/consultas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador_de_Consultas_Médicas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class consultas
    {
        [Key]
        public int idConsulta { get; set; }

        [Display(Name = "Data da consulta")]
        public string data { get; set; }

        [Display(Name = "Horário")]
        public string horario { get; set; }

        [Display(Name = "Check-in")]
        public Nullable<int> check_in { get; set; }

        [Display(Name = "Check-out")]
        public Nullable<int> check_out { get; set; }
        public int pacientes_idPaciente { get; set; }
        public int medicos_idMedico { get; set; }
        public int clinicas_idClinica { get; set; }

        public virtual pacientes pacientes { get; set; }
        public virtual medicos medicos { get; set; }
        public virtual clinicas clinicas { get; set; }
    }
}

Gerenciador de Consultas Médicas/Controllers/consultasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gerenciador_de_Consultas_Médicas.Models;

namespace Gerenciador_de_Consultas_Médicas.Controllers
{
    public class consultasController : Controller
    {
        private DominioContainer db = new DominioContainer();

        // GET: consultas
        public ActionResult Index()
        {
            agendaController agenda = new agendaController();
            agenda.deletarAgendaAntiga();

            var idUsuario = Convert.ToInt16(Session["idUsuario"]);
            var consultasSet = db.consultasSet.Where(c => c.pacientes_idPaciente == idUsuario && c.check_out != 1);
            return View(consultasSet.ToList());
        }

        // GET: consultas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            consultas consultas = db.consultasSet.Find(id);
            if (consultas == null)
            {
                return HttpNotFound();
            }
            return View(consultas);
        }

        // GET: consultas/Create
        public ActionResult Create()
        {
            ViewBag.especialidades_idEspecialidade = new SelectList(db.especialidadesSet, "idEspecialidade", "ds_especialidade");
            return View();
        }

        public ActionResult confirmarConsulta(infParaAgendaEConsultaViewModel marcar)
        {
            return View(marcar);
        }

        public ActionResult confirmarDados(string data, string horario, int cli, int med)
        {
            var idPac = Convert.ToInt16(Session["idUsuario"]);
            consultas consConfirmada = new consultas();
            consConfirmada.pacientes_idPaciente = idPac;
            consConfirmada.data = data;
            consConfirmada.horario = horario;
            consConfirmada.clinicas_idClinica = cli;
            consConfirmada.medicos_idMedico = med;

            var alterarAgenda = db.agendaSet.Where(a => a.data == data & a.horarioAtendimento == horario & 
                                                a.medicos_idMedico == med).Single();
            alterarAgenda.horarioAgendado = "Agendado";
            
            db.consultasSet.Add(consConfirmada);
            db.SaveChanges();
            return View("consultaAgendada");
        }


        // GET: consultas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            consultas consultas = db.consultasSet.Find(id);
            if (consultas == null)
            {
                return HttpNotFound();
            }
            ViewBag.pacientes_idPaciente = new SelectList(db.pacientesSet, "idPaciente", "nome", consultas.pacientes_idPaciente);
            ViewBag.medicos_idMedico = new SelectList(db.medicosSet, "idMedico", "nome", consultas.medicos_idMedico);
            ViewBag.clinicas_idClinica = new SelectList(db.clinicasSet, "idClinica", "nome", consultas.clinicas_idClinica);
            return View(consultas);
        }

        // POST: consultas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        public ActionResult reagendar(int? id, int idMed, string hora, string data)
        {
            var cancelarAgenda = db.agendaSet.Where(a => a.data == data & a.horarioAtendimento == hora &
                                                a.medicos_idMedico == idMed).Single();
            cancelarAgenda.horarioAgendado = null;

            consultas consulta = db.consultasSet.Find(id);
            db.consultasSet.Remove(consulta);
            db.SaveChanges();
            return RedirectToAction("pesquisarClinicas", "clinicas");
        }

        // GET: consultas/Delete/5
        public ActionResult Delete(int? id, int idMed, string hora, string data)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            consultas consultas = db.consultasSet.Find(id);
            if (consultas == null)
            {
                return HttpNotFound();
            }
            return View(consultas);
        }

        // POST: consultas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int idMed, string hora, string data)
        {
            consultas consultas = db.consultasSet.Find(id);

            var alterarAgenda = db.agendaSet.Where(a => a.data == data & a.horarioAtendimento == hora &
                                                a.medicos_idMedico == idMed).Single();
            alterarAgenda.horarioAgendado = null;

            db.consultasSet.Remove(consultas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult checkIn(int idConsulta, int idMedico, string data, string hora)
        {
            var consulta = db.consultasSet.Where(c => c.idConsulta == idConsulta).Single();
            consulta.check_in = 1;

            var agenda = db.agendaSet.Where(a => a.medicos_idMedico == idMedico && a.data == data && a.horarioAtendimento == hora).Single();
            agenda.horarioAgendado = "Check-in realizado";

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult checkOut(int idConsulta, int idMedico, string data, string hora)
        {
            var consulta = db.consultasSet.Where(c => c.idConsulta == idConsulta).Single();
            consulta.check_out = 1;

            var agenda = db.agendaSet.Where(a => a.medicos_idMedico == idMedico && a.data == data && a.horarioAtendimento == hora).Single();
            agenda.horarioAgendado = "Check-out realizado";

            db.SaveChanges();
            
            infAvaliacaoViewModel aval = new infAvaliacaoViewModel();
            aval.idMedico = idMedico;
            
            return RedirectToAction("Create", "avaliacoes", aval);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gerenciador de Consultas Médicas/Views/consultas/Delete.cshtml
@model Gerenciador_de_Consultas_Médicas.Models.consultas

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Deseja realmente cancelar a consulta?</h3>
<div>
    <h4>consultas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.horario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.horario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.check_in)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.check_in)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.check_out)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.check_out)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pacientes.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pacientes.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.medicos.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.medicos.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.clinicas.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.clinicas.nome)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Gerenciador de Consultas Médicas/Views/consultas/Details.cshtml
@model Gerenciador_de_Consultas_Médicas.Models.consultas

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>consultas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.horario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.horario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.check_in)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.check_in)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.check_out)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.check_out)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pacientes.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pacientes.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.medicos.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.medicos.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.clinicas.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.clinicas.nome)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idConsulta }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Gerenciador de Consultas Médicas/Views/consultas/Edit.cshtml
@model Gerenciador_de_Consultas_Médicas.Models.consultas

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>consultas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idConsulta)

        <div class="form-group">
            @Html.LabelFor(model => model.data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.horario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.horario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.horario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.check_in, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.check_in, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.check_in, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.check_out, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.check_out, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.check_out, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pacientes_idPaciente, "pacientes_idPaciente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("pacientes_idPaciente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.pacientes_idPaciente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.medicos_idMedico, "medicos_idMedico", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("medicos_idMedico", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.medicos_idMedico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.clinicas_idClinica, "clinicas_idClinica", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("clinicas_idClinica", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.clinicas_idClinica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Gerenciador de Consultas Médicas/Views/consultas/Index.cshtml
@model IEnumerable<Gerenciador_de_Consultas_Médicas.Models.consultas>

@{
    ViewBag.Title = "Index";
}

<h2>Consultas</h2>

<p>
    @Html.ActionLink("Marcar consulta", "pesquisarClinicas", "clinicas")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.clinicas.nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.medicos.nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.data)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.horario)
        </th>
        <th>
        </th>
        <th>
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.clinicas.nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.medicos.nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.data)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.horario)
        </td>
        <td>
            @Html.ActionLink("Check-in", "checkIn", "consultas", new
            {
                @class = "checkIn",
                idConsulta = item.idConsulta,
                idMedico = item.medicos_idMedico,
                data = item.data,
                hora = item.horario
            },
           new { @class = "btn btn-primary btn-sm", id = "checkIn", onclick = "habilitaCheckOut();" })
        </td>
        <td>
            @Html.ActionLink("Check-out", "checkOut", "consultas", new
            {
                idConsulta = item.idConsulta,
                idMedico = item.medicos_idMedico,
                data = item.data,
                hora = item.horario
            },
            new { @class = "btn btn-primary btn-sm", id = "checkOut" })
        </td>

        <td>
            @Html.ActionLink("Reagendar consulta", "reagendar", new
            {
                id = item.idConsulta,
                idMed = item.medicos_idMedico,
                hora = item.horario,
                data = item.data
            }) |
                 @Html.ActionLink("Cancelar consulta", "Delete", new
            {
                id = item.idConsulta,
                idMed = item.medicos_idMedico,
                hora = item.horario,
                data = item.data
            })
        </td>
    </tr>
}

</table>

Gerenciador de Consultas Médicas/Views/consultas/confirmarConsulta.cshtml
@model Gerenciador_de_Consultas_Médicas.Models.infParaAgendaEConsultaViewModel

@{
    ViewBag.Title = "confirmarConsulta";
}

<h2>Confirmar consulta</h2>

@using (Html.BeginForm())
{
    <div>
        <h4>
            Deseja confirmar o agendamento da consulta com o(a) médico(a) @Html.DisplayFor(model => model.nomeMedico)
            para o dia @Html.DisplayFor(model => model.data) às @Html.DisplayFor(model => model.horarios)?
        </h4>
    </div>
    <div class="form-group">
        @Html.ActionLink("Confirmar", "confirmarDados", new
        {
            data = Model.data,
            horario = Model.horarios,
            cli = Model.idClinica,
            med = Model.idMedico
        }) 
        <a href="javascript:void(0);" onclick="history.go(-1);">Cancelar</a>     
    </div>
}

Gerenciador de Consultas Médicas/Views/consultas/consultaAgendada.cshtml
@{
    ViewBag.Title = "consultaAgendada";
}

<h3>A consulta foi agendada com sucesso</h3>

@Html.ActionLink("Voltar", "Index")